CFLAGS = -g
all: clibrary_test1 clibrary_test2 syscall_test1 syscall_test2

clean:
	rm clibrary_test1 clibrary_test2 syscall_test1 syscall_test2 t1.dat t2.dat

clibrary_test1 : clibrary_test1.c

clibrary_test2 : clibrary_test2.c

syscall_test1 : syscall_test1.c

syscall_test2 : syscall_test2.c

